import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

import { api } from "~/utils/api";

import { v4 as uuid } from "uuid";

const Home: NextPage = () => {
  const {data: menu} = api.menu.getAll.useQuery();

  console.log(menu)

  const [currentUuid, setCurrentUuid] = useState("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener('beforeunload', (event) => {
        console.log("updating store status to unknown")
       });
    }

    setCurrentUuid(uuid());
  }, [])

  const getNewUuid = () => {
    setCurrentUuid(uuid())
  };

  console.log(currentUuid)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <button onClick={getNewUuid}>GET NEW</button>
      </main>
    </>
  );
};

export default Home;
