import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

import { api } from "~/utils/api";

import { v4 as uuid } from "uuid";
import { SignIn } from "@clerk/nextjs";

const Home: NextPage = () => {
  const [currentUuid, setCurrentUuid] = useState("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener('beforeunload', (event) => {
        console.log("updating store status to unknown")
       });
    }

    setCurrentUuid(uuid());
  }, [])

  const getNewUuid = () => {
    setCurrentUuid(uuid())
  };

  console.log(currentUuid)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <button onClick={getNewUuid}>GET NEW</button>
          <SignIn
          appearance={{
            variables: {
              colorBackground: "#20222e",
              colorText: "#ffffff",
              colorPrimary: "#6C47FF",
              fontWeight: { normal: 300 },
              colorInputBackground: "#292c3e",
              colorInputText: "#ffffff"
            }
          }}
        />
      </main>
    </>
  );
};

export default Home;
